version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app   # Amazon Linux 경로로 수정
file_exists_behavior: OVERWRITE # 덮어쓰기 허용

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user                 # ec2-user로 권한 수정
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user                 # ec2-user로 권한 수정